name: C++ Build Tests

on: [push, pull_request]

jobs:
  build-test-question1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install g++
        run: sudo apt-get install g++

      - name: Compile Question1
        run: g++ Question1.cpp -o question1.out

  build-test-question2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install g++
        run: sudo apt-get install g++

      - name: Compile Question2
        run: g++ Question2.cpp -o question2.out
